# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: My computery blog/archive
description: Keeping the computery thoughts in this blog to help me process, reflect, and figure out what I would like to do right now
github_username: Tenatic-X

# Email and twitter are optional:
email: deanckbusiness@gmail.com
twitter_username:

# Set this to true to get LaTeX math equation support
use_math:

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge


--- 
# Only the main Sass file needs front matter (the dashes are enough) 
---

// We import the light theme first.
@import "minima/skins/classic";

// We define css variables based on theme color
:root {
  --brand-color :           #{$brand-color};
  --brand-color-light :     #{$brand-color-light};
  --brand-color-dark :      #{$brand-color-dark};

  --site-title-color :      #{$site-title-color};

  --text-color :            #{$text-color};
  --background-color :      #{$background-color};
  --code-background-color : #{$code-background-color};

  --link-base-color:        #{$link-base-color};
  --link-visited-color:     #{$link-visited-color};
  --link-hover-color:       #{$link-hover-color};

  --border-color-01:        #{$border-color-01};
  --border-color-02:        #{$border-color-02};
  --border-color-03:        #{$border-color-03};

  --table-text-color:       #{$table-text-color};
  --table-zebra-color:      #{$table-zebra-color};
  --table-header-bg-color:  #{$table-header-bg-color};
  --table-header-border:    #{$table-header-border};
  --table-border-color:     #{$table-border-color};
}

// now we redefine those variables to use css variables with a fallback
$brand-color:           var(--brand-color,$brand-color); 
$brand-color-light:     var(--brand-color-light,$brand-color-light); 
$brand-color-dark:      var(--brand-color-dark,$brand-color-dark); 

$site-title-color:      var(--site-title-color,$site-title-color);

$text-color:            var(--text-color,$text-color);
$background-color:      var(--background-color,$background-color);
$code-background-color: var(--background-color,$code-background-color);

$link-base-color:       var(--link-base-color,$link-base-color);
$link-visited-color:    var(--link-visited-color,$link-visited-color);
$link-hover-color:      var(--link-hover-color,$link-hover-color);

$border-color-01:       var(--border-color-01,$border-color-01);
$border-color-02:       var(--border-color-02,$border-color-02);
$border-color-03:       var(--border-color-03,$border-color-03);

$table-text-color:      var(--table-text-color,$table-text-color);
$table-zebra-color:     var(--table-zebra-color,$table-zebra-color);
$table-header-bg-color: var(--table-header-bg-color,$table-header-bg-color);
$table-header-border:   var(--table-header-border,$table-header-border);
$table-border-color:    var(--table-border-color,$table-border-color);

// Now we proceed with minima.
@import "minima/initialize";


// Define media query for dark theme users.
@media (prefers-color-scheme: dark) {

// Import dark skin.
// We will have to alter it as well.
// It gives our variables new meaning yet again.
// But you have to remove  "!default" a the end of variable declarations in dark skin.
  @import "minima/skins/dark";

  :root {
    --brand-color :           #{$brand-color};
    --brand-color-light :     #{$brand-color-light};
    --brand-color-dark :      #{$brand-color-dark};
  
    --site-title-color :      #{$site-title-color};
  
    --text-color :            #{$text-color};
    --background-color :      #{$background-color};
    --code-background-color : #{$code-background-color};
  
    --link-base-color:        #{$link-base-color};
    --link-visited-color:     #{$link-visited-color};
    --link-hover-color:       #{$link-hover-color};
  
    --border-color-01:        #{$border-color-01};
    --border-color-02:        #{$border-color-02};
    --border-color-03:        #{$border-color-03};
  
    --table-text-color:       #{$table-text-color};
    --table-zebra-color:      #{$table-zebra-color};
    --table-header-bg-color:  #{$table-header-bg-color};
    --table-header-border:    #{$table-header-border};
    --table-border-color:     #{$table-border-color};
  }
}
